# Generated by Django 5.1.4 on 2024-12-11 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais', models.CharField(blank=True, max_length=50)),
                ('fundacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('ano_lancamento', models.PositiveIntegerField()),
                ('desenvolvedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.desenvolvedor')),
            ],
        ),
    ]
